# Generated by Django 4.2.16 on 2024-10-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(verbose_name='Оригинальная ссылка')),
                ('short_code', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
